<?php

/**
 * @file
 * ldnddev Slider Module file.
 */

/**
 * Implements hook_theme().
 */
function ldnddev_slider_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__ldnddev_slider' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__ldnddev_slider_image' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__ldnddev_slider_video' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__ldnddev_slider' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__ldnddev_slider_item' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__ldnddev_slider_image' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__ldnddev_slider_video' => [
      'base hook' => 'paragraph',
    ],
    'media__remote_video' => [
      'base hook' => 'paragraph',
    ],
    'field__media__remote_video' => [
      'base hook' => 'paragraph',
    ],
  ];
}
